config/routes.rb
Rails.application.routes.draw do

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
    devise_for :users
    devise_for :hosts

    root 'pages#home'

    resources :users
    resources :listings, only: [:show] do  #use show to user they're not admin
      resources :bookings do #this part is nexted resources
        get 'success'
        get 'cancel'
        get 'payment_details'
      end
    end

    namespace :platform do #from slides (for host/admin)
      get '/home', to: 'pages#host_homepage'

      resources :dashboards, only: [:show]
      resources :hosts #points to edit_platform_host_path _platform.html.erb
      resources :listings do
        member do #add member here to get the listing id
          delete :delete_photo_attachment #action method name insid elisting controller
        end
      end
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :listing #create associations

  delegate :host, to: :listing #to get/to know the details of hosts

  enum status: [:pending, :paid, :cancelled] #enum - enumerable status (from booking columns)

  after_create :generate_ref_no  #after booking ref.no will be created
  after_create :calculate_total #

  def generate_ref_no   #method to generate references no. for bookings
    #y7w40p - example
    random_string = SecureRandom.hex(3)
    self.ref_no = random_string
    self.save
  end

  def calculate_total #method to calculate the totals
    days_between = (check_out_date.to_date - check_in_date.to_date).to_i
    total_days = days_between + 1
    self.total = listing.price_per_day * total_days
    self.save
  end
end

app/models/host.rb
class Host < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :listings, dependent: :destroy
  has_many :bookings, through: :listings
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :host
  has_many_attached :photos

  has_many :bookings
  
  scope :is_available, -> {where(available:true ) } #to filter data to get only available
end


#plural nouns: photos
#model - routes - controller

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :avatar
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < UsersController
  def create
    @listing = Listing.find(params[:listing_id])
    @booking = @listing.bookings.create(booking_params.merge(user_id: current_user.id))

    if @booking.save
      redirect_to user_path(current_user), notice: 'Booking was successfully created.'
    else
      redirect_to listing_path(@listing), alert: 'There was an error. Please try again.'
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  def success
  end

  def cancel
  end

  private
   def booking_params
     params.require(:booking).permit(:check_in_date, :check_out_date)
   end

end

app/controllers/listings_controller.rb
class ListingsController < UsersController
  def show
    @listing = Listing.find(params[:id])
    @booking = Booking.new
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #skip_before_action :authenticate_user!

  def home
  end

end

app/controllers/platform/dashboards_controller.rb
class Platform::DashboardsController < PlatformController

  def show
    @listing = Listing.new
    @listings = current_host.listings
  end
end

app/controllers/platform/hosts_controller.rb
class Platform::HostsController < PlatformController

  def edit
  end

end

app/controllers/platform/listings_controller.rb
class Platform::ListingsController < PlatformController

  def create
    @listing = current_host.listings.create(listing_params)

    if @listing.save
      redirect_to platform_home_path, notice: 'Listing was succesfully created.'
    else
      redirect_to platform_home_path, notice: 'Listing was error. Please try again.'
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    @listing.update(listing_params)

    if @listing.save
      redirect_to platform_dashboard_path(current_host), notice: 'Listing was successfully updated.'
    else
      redirect_to platform_dashboard_path(current_host), alert: 'There was an error. Please try again.'
    end
  end

  def delete_photo_attachment #to delete a single id
    @image = ActiveStorage::Attachment.find(params[:id])
    @image.purge
    redirect_to platform_dashboard_path(current_host), notice: 'Photo was successfully removed.'
  end

  private
    def listing_params
      params.require(:listing).permit(:title, :description, :price_per_day, :available, :location, :latitude, :longtitude, photos: [])
    end
end

app/controllers/platform/pages_controller.rb
class Platform::PagesController < PlatformController

  def host_homepage
    @listing = Listing.new #create variables
  end

end

app/controllers/platform_controller.rb
class PlatformController < ApplicationController
  before_action :authenticate_host!

  layout 'platform' #inheirt from platform
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  # before_action :set_user, only: [:show, :edit, :update]

  layout 'user'

  def show
    @user = User.find(params[:id])
    @listings = Listing.is_available #check listing.rb
    @bookings = @user.bookings
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)

    if @user.save
      redirect_to user_path(current_user), notice: 'User profile was successfully updated.'
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:avatar)
  end

  #
  # def set_user
  #   @user = User.find(params[:id])
  # end  [mins - 1:48:00]

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/cancel.html.erb
<h1>Payment was cancelled</h1>

app/views/bookings/payment_details.html.erb
<p><%= @payment['id'] %></p>
<p><%= @charges['payment_method_details']['card']['network'] %></p>

app/views/bookings/show.html.erb
<section class='single-booking-page'>
  <div class='listing-details'>
    <h1>Listing Details</h1>
    <p>Host: <%= @booking.host.email %></p>
    <p>Destination: <%= @booking.listing.title %></p>
    <p>Location: <%= @booking.listing.location %></p>
  </div>

  <div class='booking-details'>
    <h1>Booking details</h1>
    <p>Reference No. <%= @booking.ref_no %></p>
    <p>Check in: <%= @booking.check_in_date %></p>
    <p>Check out: <%= @booking.check_out_date %></p>
    <p>total: <%= @booking.total %></p>
    <p>status: <%= @booking.status %></p>
  </div>

  <% if @booking.status == 'pending' %>
    <div class='booking-payment'>
      <%= form_with url: '/stripes', method: :post do |f| %>
        <%= f.text_field :booking_id, value: "#{@booking.id}", hidden: true %>
        <%= f.submit 'Confirm Booking'%>
      <% end %>
    </div>
  <% elsif @booking.status == 'cancelled' %>
    <p>This Booking has been cancelled.</p>
  <% else %>
    <button>
      <%= link_to 'View payment details', listing_booking_payment_details_path(@booking.listing, @booking)%>
    </button>
  <% end %>
</section>

app/views/bookings/success.html.erb
<h1>Payment successful</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Platform-AirbnbCloneAug</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/platform.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Host-AirbnbCloneAug</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async defer data-turbolinks-eval="false" src="https://maps.googleapis.com/maps/api/js?key=<%=Rails.application.credentials[Rails.env.to_sym][:GOOGLE_MAP_API]%>&libraries=places&callback=initMap"></script>

  </head>

  <body>
    <%= render 'shared/platform_header' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>


<%#copy from ApplicationController %>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AirbnbCloneAug</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p><%= render 'shared/header' %></p>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/listings/show.html.erb
<section class='single-listing-show-page'>
  <div class='listing-details'>
    <% if @listing.photos.attached? %>
      <% @listing.photos.each do |photo| %>
        <%= image_tag photo, style: 'width: 200px;'%>
      <% end %>
    <% end %>
    <p>Title: <%= @listing.title %></p>
    <p>Description: <%= @listing.description %></p>
    <p>Price Per Day: <%= @listing.price_per_day %></p>
    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{@listing.latitude},#{@listing.longitude}&key=#{Rails.application.credentials[Rails.env.to_sym][:GOOGLE_MAP_API]}", alt: "Map" %>
    <br>
    <%= link_to 'Get Direction', "https://maps.google.com/?q=#{@listing.latitude},#{@listing.longitude}", target: '_blank' %>
    <br>
  </div>

  <div class='booking-form'>
    <h2>Booking section</h2>
    <%= form_with(model: [@listing, @booking]) do |f| %>
      <%= f.label :check_in_date %>
      <%= f.date_field :check_in_date %>
      <%= f.label :check_out_date %>
      <%= f.date_field :check_out_date %>
      <%= f.submit 'Confirm' %>
    <% end %>
  </div>
</section>
<%# copy from users/show.html.erb MINS 01:51:00 %>

app/views/pages/home.html.erb
<%= render 'shared/header' %>
<h1>Welcome</h1>

app/views/pages/host_homepage.html.erb
<h1>Host Homepage</h1>

app/views/platform/dashboards/show.html.erb
<h1>Host Dashboard</h1>

<section class='new-listing-form'>
  <%= form_with(model: [:platform, @listing], data: { controller: 'location', action: 'google-maps-callback@window->location.initMap' }) do |f| %>
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :price_per_day %>
    <%= f.text_field :price_per_day %>
    <%= f.label :location %>
    <%= f.text_field :location, data: { location_target: 'field' } %>
    <%= f.hidden_field :latitude, data: { location_target: 'latitude' } %>
    <%= f.hidden_field :longitude, data: { location_target: 'longitude' } %>
    <%= f.label :available %>
    <%= f.check_box :available %>
    <%= f.submit 'create' %>
    <div class='google-map' style='margin-top: 10px;'>
      <div data-location-target='map' style='height: 400px'></div>
    </div>
  <% end %>
</section>

<section class='host-listings'>
  <h2>All your listings</h2>
  <% @listings.each do |listing| %>
    <% if listing.photos.attached? %>
      <% listing.photos.each do |photo| %>
        <%= image_tag photo, style: 'width: 200px;'%>
        <%= link_to 'Remove', delete_photo_attachment_platform_listing_path(photo), method: :delete, data: { confirm: 'Are you sure?' }%>
      <% end %>
    <% end %>
    <p>Title: <%= listing.title %></p>
    <p>Description: <%= listing.description %></p>
    <p>Price per day: <%= listing.price_per_day %></p>
    <%= link_to edit_platform_listing_path(listing) do %>
      <button>Edit</button>
    <% end %>
    <br> <%# static page %>
    <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{listing.latitude},#{listing.longitude}&key=#{Rails.application.credentials[Rails.env.to_sym][:GOOGLE_MAP_API]}", alt: "Map" %>
    <br>
    <%= link_to 'Get Direction', "https://maps.google.com/?q=#{listing.latitude},#{listing.longitude}", target: '_blank' %>
    <br>
  <% end %>
</section>

app/views/platform/hosts/edit.html.erb
<section class='host-edit-page'>
  <h1>Host Setting Page</h1>
</section>

app/views/platform/listings/edit.html.erb
<h1>Listing Edit Page</h1>

<section class='edit-listing-form'>
  <%= form_with(model: [:platform, @listing], data: { controller: 'location', action: 'google-maps-callback@window->location.initMap' }) do |f| %>
    <%= f.label :photos %>
    <%= f.file_field :photos, multiple: true %>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <%= f.label :description %>
    <%= f.text_field :description %>
    <%= f.label :price_per_day %>
    <%= f.text_field :price_per_day %>
    <%= f.label :location %>
    <%= f.text_field :location, data: { location_target: 'field' } %>
    <%= f.hidden_field :latitude, data: { location_target: 'latitude' } %>
    <%= f.hidden_field :longitude, data: { location_target: 'longitude' } %>
    <%= f.label :available %>
    <%= f.check_box :available %>
    <%= f.submit 'create' %>
    <div class='google-map' style='margin-top: 10px;'>
      <div data-location-target='map' style='height: 400px'></div>
    </div>
  <% end %>
</section>

app/views/shared/_flash.html.erb
<section class='flash-message'>
  <% flash.each do |key, value| %>
    <%= value %>
  <% end %>
</section>

app/views/shared/_form_error.html.erb
<section class='form-error'>
  <% if object.errors.any? %>
    <% object.errors.each do |error| %>
      <%= error.full_message %>
    <% end %>
  <% end %>
</section>

app/views/shared/_header.html.erb
<section class='navbar'>
  <button>
    <%= link_to 'Home', root_path %>
  </button>

  <% if user_signed_in? %>
    <button>
      <%= link_to 'Profile', user_path(current_user) %>
    </button>
    <button>
      <%= link_to 'Setting', edit_user_path(current_user) %>
    </button>
    <button>
      <%= link_to 'Logout', destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </button>
  <% else %>
    <button>
      <%= link_to 'Sign Up', new_user_registration_path %>
    </button>
    <button>
      <%= link_to 'Login', new_user_session_path %>
    </button>
    <button>
      <%= link_to 'Become a host', platform_home_path %>
    </button>
  <% end %>
</section>

app/views/shared/_platform_header.html.erb
<section class='platform_header'>
  <button>
    <%= link_to 'Home', root_path %>
  </button>

  <% if host_signed_in? %>
    <button>
      <%= link_to 'Dashboard', platform_dashboard_path(current_host) %>
    </button>
    <button>
      <%= link_to 'Profile', platform_home_path %>
    </button>
    <button>
      <%= link_to 'Setting', edit_platform_host_path(current_host) %>
    </button>
    <button>
      <%= link_to 'Logout', destroy_host_session_path, method: :delete, data: { confirm: 'Are you sure?' } %>
    </button>
  <% else %>
    <button>
      <%= link_to 'Sign Up', new_host_registration_path %>
    </button>
    <button>
      <%= link_to 'Login', new_host_session_path %>
    </button>
  <% end %>
</section>

app/views/users/edit.html.erb
<h1>Profile Setting</h1>

<section class='user-setting-form'>
  <%= form_with(model: @user) do |f| %>
    <%= render 'shared/form_error', object: @user %>
    <%= f.label :avatar %>
    <%= f.file_field :avatar %>
    <%= f.submit 'save' %>
  <% end %>
</section>

app/views/users/show.html.erb
<section class='user-profile'>
  <div class='user-avatar'>
    <% if @user.avatar.attached? %>
      <%= image_tag @user.avatar, style: 'width: 200px;' %>
    <% end %>
  </div>
  <div class='user-details'>
    <h2>Hello, <%= @user.email %></h2>
  </div>
  <br>
  <%# show the users bookings details %>
  <div class='user-bookings'>
    <h1>Your Bookings Details</h1>
    <% @bookings.each do |booking| %>
      <p>Ref. No: <%= link_to "#{booking.ref_no}", listing_booking_path(booking.listing, booking) %></p>
      <p>Status: <%= booking.status %></p>
      <p>Total: <%= booking.total %></p>
    <% end %>
  </div>

  <br>

  <div class="all-available-listing">
    <h1>You might be interested</h1>
    <% @listings.each do |listing| %>
      <% if listing.photos.attached? %>
        <% listing.photos.each do |photo| %>
          <%= image_tag photo, style: 'width: 200px;'%>
        <% end %>
      <% end %>
      <p>Title: <%= listing.title %></p>
      <p>Description: <%= listing.description %></p>
      <p>Price Per Day: <%= listing.price_per_day %></p>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?zoom=17&size=400x300&markers=size:small%7Ccolor:red%7C#{listing.latitude},#{listing.longitude}&key=#{Rails.application.credentials[Rails.env.to_sym][:GOOGLE_MAP_API]}", alt: "Map" %>
      <br>
      <p><%= link_to 'Get Direction', "https://maps.google.com/?q=#{listing.latitude},#{listing.longitude}", target: '_blank' %></p>
      <%= link_to listing_path(listing) do %>
        <p><button>Booking</button></p>
      <% end %>
    <% end %>
  </div>
</section>